# Generated by Django 5.2.7 on 2025-10-25 10:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0006_delete_testset'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=10)),
                ('tests', models.JSONField(default=list)),
                ('is_private', models.BooleanField(default=False, help_text='If true, only selected users and groups can access this test.')),
                ('start_time', models.DateTimeField(blank=True, help_text='When the test becomes available.', null=True)),
                ('end_time', models.DateTimeField(blank=True, help_text='When the test closes.', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('allowed_groups', models.ManyToManyField(blank=True, help_text='Groups that are allowed to access this test.', related_name='group_tests', to='accounts.group')),
                ('assigned_users', models.ManyToManyField(blank=True, help_text='Users who are allowed to take this test if private.', related_name='assigned_tests', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(help_text='The teacher or user who created this test.', on_delete=django.db.models.deletion.CASCADE, related_name='created_tests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
