# Generated by Django 5.2.7 on 2025-10-26 07:54

import django.contrib.postgres.fields
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_delete_testset'),
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CodingChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(help_text='Full problem description and constraints.')),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=10)),
                ('languages', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, default=list, size=None)),
                ('test_cases', models.JSONField(default=list, help_text="List of test cases with 'input' and 'expected_output'. Example: [{'input': '2 3', 'expected_output': '5'}]")),
                ('max_score', models.PositiveIntegerField(default=100)),
                ('time_limit', models.FloatField(default=1.0, help_text='Time limit per test case in seconds.')),
                ('memory_limit', models.PositiveIntegerField(default=256, help_text='Memory limit per test in MB.')),
                ('is_private', models.BooleanField(default=False, help_text='If true, only assigned users and groups can access this challenge.')),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('allowed_groups', models.ManyToManyField(blank=True, related_name='group_challenges', to='accounts.group')),
                ('assigned_users', models.ManyToManyField(blank=True, related_name='coding_challenges', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_challenges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
