# Generated by Django 5.2.7 on 2025-10-29 15:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_delete_testset'),
        ('tasks', '0004_codingchallenge_autocheck_testsubmission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChallengeGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('is_private', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('allowed_groups', models.ManyToManyField(blank=True, related_name='allowed_challenge_groups', to='accounts.group')),
                ('assigned_users', models.ManyToManyField(blank=True, related_name='assigned_challenge_groups', to=settings.AUTH_USER_MODEL)),
                ('challenges', models.ManyToManyField(blank=True, related_name='groups', to='tasks.codingchallenge')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_challenge_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
