# Generated by Django 5.2.7 on 2025-10-29 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_challengegroup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codingchallenge',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='codingchallenge',
            name='start_time',
        ),
    ]
