# Generated by Django 5.2.8 on 2025-11-13 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_remove_codingchallenge_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testsubmission',
            name='meta',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
