# Generated by Django 5.2.8 on 2025-11-13 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_remove_codingchallenge_end_time_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=(
                        "ALTER TABLE tasks_testsubmission "
                        "ADD COLUMN IF NOT EXISTS meta jsonb "
                        "DEFAULT '{}'::jsonb"
                    ),
                    reverse_sql=(
                        "ALTER TABLE tasks_testsubmission "
                        "DROP COLUMN IF EXISTS meta"
                    ),
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='testsubmission',
                    name='meta',
                    field=models.JSONField(blank=True, default=dict, null=True),
                ),
            ],
        ),
    ]
