# Generated by Django 5.2.8 on 2025-11-25 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_testsubmission_meta'),
    ]

    operations = [
        migrations.AddField(
            model_name='codesubmission',
            name='meta',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
